desc_mapping_path = "../data/desc_mapping"
label_mapping_path = "../data/label_mapping"
distance_mapping_path = "../data/distance_mapping"
adjacency_list_path = "../data/adjacency_list"
distance_method = "labels_descriptions"
entity_limit = 100
wembed_api = "http://127.0.0.1:5001/distance"
wikidata_api = "http://127.0.0.1:5000"
query_file_paths = ["../data/wikidata_queries_10000_topics_genre.csv"]

optimizer_iterations = 150
optimizer_sample_percentage = 0.2
optimizer_results_path = "../data/optimizer_results.csv"

benchmark_results_path = "../data/benchmark_results"
